---

# Main tasks file for elk-node role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::elk-node'
    - 'role::elk-node::init'


- name: 'ELK-NODE | Deploy Docker compose project'
  include_role:
    name: 'infopen.docker-service__1.0.1'
  tags:
    - 'role::elk-node'
    - 'role::elk-node::service'
  vars:
    _ansistrano_git_repo: "{{ elk_node_git_repo }}"
    _ansistrano_git_branch: "{{ elk_node_git_branch }}"
    _docker_service_project_name: 'elk_node'
    _docker_service_templates: "{{ elk_node_templates }}"
    _docker_service_networks: "{{ elk_node_networks }}"
    _docker_service_volumes: "{{ elk_node_volumes }}"
